# uses Algerian Forest Fires Dataset

In [6]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [16]:
df=pd.read_csv("Algerian_forest_fires_dataset.csv",header=1)
df.head()

   1  6  2012  29  57  18     0  65.7  3.4   7.6  1.3 3.4.1  0.5  not fire
0  2  6  2012  29  61  13   1.3  64.4  4.1   7.6    1   3.9  0.4  not fire
1  3  6  2012  26  82  22  13.1  47.1  2.5   7.1  0.3   2.7  0.1  not fire
2  4  6  2012  25  89  13   2.5  28.6  1.3   6.9    0   1.7    0  not fire
3  5  6  2012  27  77  16     0  64.8    3  14.2  1.2   3.9  0.5  not fire
4  6  6  2012  31  67  14     0  82.6  5.8  22.2  3.1     7  2.5      fire

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 246 entries, 0 to 245
Data columns (total 14 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   1            245 non-null    object
 1   6            244 non-null    object
 2   2012         244 non-null    object
 3   29           244 non-null    object
 4   57           244 non-null    object
 5   18           244 non-null    object
 6   0            244 non-null    object
 7   65.7         244 non-null    object
 8   3.4          244 non-null    object
 9   7.6          244 non-null    object
 10  1.3          244 non-null    object
 11  3.4.1        244 non-null    object
 12  0.5          244 non-null    object
 13  not fire     243 non-null    object
dtypes: object(14)
memory usage: 27.0+ KB

In [22]:
#data cleaning
df[df.isnull().any(axis=1)]

,1,6,2012,29,57,18,0,65.7,3.4,7.6,1.3,3.4.1,0.5,not fire
121,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
122,Sidi-Bel Abbes Region Dataset,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
167,14,7,2012,37,37,18,0.2,88.9,12.9,14.6 9,12.5,10.4,fire,NaN

In [23]:
df.loc[:122,"Region"]=0
df.loc[122:,"Region"]=1

In [24]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 246 entries, 0 to 245
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   1            245 non-null    object
 1   6            244 non-null    object
 2   2012         244 non-null    object
 3   29           244 non-null    object
 4   57           244 non-null    object
 5   18           244 non-null    object
 6   0            244 non-null    object
 7   65.7         244 non-null    object
 8   3.4          244 non-null    object
 9   7.6          244 non-null    object
 10  1.3          244 non-null    object
 11  3.4.1        244 non-null    object
 12  0.5          244 non-null    object
 13  not fire     243 non-null    object
 14  Region       246 non-null    float64
dtypes: float64(1), object(14)
memory usage: 29.0+ KB

In [25]:
df[['Region']]=df[['Region']].astype(int)

In [26]:
df.head()

,1,6,2012,29,57,18,0,65.7,3.4,7.6,1.3,3.4.1,0.5,not fire,Region
0,2,6,2012,29,61,13,1.3,64.4,4.1,7.6,1,3.9,0.4,not fire,0
1,3,6,2012,26,82,22,13.1,47.1,2.5,7.1,0.3,2.7,0.1,not fire,0
2,4,6,2012,25,89,13,2.5,28.6,1.3,6.9,0,1.7,0,not fire,0
3,5,6,2012,27,77,16,0,64.8,3,14.2,1.2,3.9,0.5,not fire,0
4,6,6,2012,31,67,14,0,82.6,5.8,22.2,3.1,7,2.5,fire,0

In [27]:
#remove the null values or NaN 
df.dropna(inplace=True)
df.head()

,1,6,2012,29,57,18,0,65.7,3.4,7.6,1.3,3.4.1,0.5,not fire,Region
0,2,6,2012,29,61,13,1.3,64.4,4.1,7.6,1,3.9,0.4,not fire,0
1,3,6,2012,26,82,22,13.1,47.1,2.5,7.1,0.3,2.7,0.1,not fire,0
2,4,6,2012,25,89,13,2.5,28.6,1.3,6.9,0,1.7,0,not fire,0
3,5,6,2012,27,77,16,0,64.8,3,14.2,1.2,3.9,0.5,not fire,0
4,6,6,2012,31,67,14,0,82.6,5.8,22.2,3.1,7,2.5,fire,0

In [32]:
df.isnull().sum()

1              0
6              0
2012           0
29             0
57             0
18             0
0              0
65.7           0
3.4            0
7.6            0
1.3            0
3.4.1          0
0.5            0
not fire       0
Region         0
dtype: int64