##### "Travel.Com" company wants to enable and establish a viable business model to expand the customer base. One of the ways to expand the customer base is to introduce a new offering of packages. Currently, there are 5 types of packages the company is offering - Basic, Standard, Deluxe, Super Deluxe, King. Looking at the data of the last year, we observed that 18% of the customers purchased the packages. However, the marketing cost was quite high because customers were contacted at random without looking at the available information. The company is now planning to launch a new product i.e. Wellness Tourism Package. Wellness Tourism is defined as Travel that allows the traveler to maintain, enhance or kick-start a healthy lifestyle, and support or increase one's sense of well-being.However, this time company wants to harness the available data of existing and potential customers to make the marketing expenditure more efficient

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import warnings
warnings.filterwarnings("ignore")

In [2]:
df=pd.read_csv("Travel.csv")
df.head()

,CustomerID,ProdTaken,Age,TypeofContact,CityTier,DurationOfPitch,Occupation,Gender,NumberOfPersonVisiting,NumberOfFollowups,ProductPitched,PreferredPropertyStar,MaritalStatus,NumberOfTrips,Passport,PitchSatisfactionScore,OwnCar,NumberOfChildrenVisiting,Designation,MonthlyIncome
0,200000,1,41.0,Self Enquiry,3,6.0,Salaried,Female,3,3.0,Deluxe,3.0,Single,1.0,1,2,1,0.0,Manager,20993.0
1,200001,0,49.0,Company Invited,1,14.0,Salaried,Male,3,4.0,Deluxe,4.0,Divorced,2.0,0,3,1,2.0,Manager,20130.0
2,200002,1,37.0,Self Enquiry,1,8.0,Free Lancer,Male,3,4.0,Basic,3.0,Single,7.0,1,3,0,0.0,Executive,17090.0
3,200003,0,33.0,Company Invited,1,9.0,Salaried,Female,2,3.0,Basic,3.0,Divorced,2.0,1,5,1,1.0,Executive,17909.0
4,200004,0,NaN,Self Enquiry,1,8.0,Small Business,Male,2,3.0,Basic,4.0,Divorced,1.0,0,5,1,0.0,Executive,18468.0

## Data Cleaning
### Handling Missing values
#### 1.Handling Missing values
#### 2. Handling Duplicates
#### 3.Check data types
#### 4. Understand the dataset

In [3]:
df.isnull().sum()

CustomerID                    0
ProdTaken                     0
Age                         226
TypeofContact                25
CityTier                      0
DurationOfPitch             251
Occupation                    0
Gender                        0
NumberOfPersonVisiting        0
NumberOfFollowups            45
ProductPitched                0
PreferredPropertyStar        26
MaritalStatus                 0
NumberOfTrips               140
Passport                      0
PitchSatisfactionScore        0
OwnCar                        0
NumberOfChildrenVisiting     66
Designation                   0
MonthlyIncome               233
dtype: int64

In [4]:
df['Gender'].value_counts()

Gender
Male       2916
Female     1817
Fe Male     155
Name: count, dtype: int64

In [5]:
df['MaritalStatus'].value_counts()

MaritalStatus
Married      2340
Divorced      950
Single        916
Unmarried     682
Name: count, dtype: int64

In [6]:
df['TypeofContact'].value_counts()

TypeofContact
Self Enquiry       3444
Company Invited    1419
Name: count, dtype: int64

In [7]:
df['CityTier'].value_counts()

CityTier
1    3190
3    1500
2     198
Name: count, dtype: int64

In [8]:
df['CustomerID'].value_counts()

CustomerID
200000    1
203256    1
203263    1
203262    1
203261    1
         ..
201628    1
201627    1
201626    1
201625    1
204887    1
Name: count, Length: 4888, dtype: int64

In [9]:
df['Designation'].value_counts()

Designation
Executive         1842
Manager           1732
Senior Manager     742
AVP                342
VP                 230
Name: count, dtype: int64

In [10]:
df['DurationOfPitch'].value_counts()

DurationOfPitch
9.0      483
7.0      342
8.0      333
6.0      307
16.0     274
15.0     269
14.0     253
10.0     244
13.0     223
11.0     205
12.0     195
17.0     172
30.0      95
22.0      89
31.0      83
23.0      79
18.0      75
29.0      74
32.0      74
25.0      73
21.0      73
27.0      72
26.0      72
24.0      70
35.0      66
20.0      65
28.0      61
33.0      57
19.0      57
34.0      50
36.0      44
5.0        6
126.0      1
127.0      1
Name: count, dtype: int64

In [11]:
df['MonthlyIncome'].value_counts()

MonthlyIncome
20855.0    7
21288.0    7
17342.0    7
21020.0    7
24950.0    6
          ..
17074.0    1
24250.0    1
21077.0    1
24714.0    1
21471.0    1
Name: count, Length: 2475, dtype: int64

In [12]:
df['NumberOfChildrenVisiting'].value_counts()

NumberOfChildrenVisiting
1.0    2080
2.0    1335
0.0    1082
3.0     325
Name: count, dtype: int64

In [13]:
df["NumberOfFollowups"].value_counts()

NumberOfFollowups
4.0    2068
3.0    1466
5.0     768
2.0     229
1.0     176
6.0     136
Name: count, dtype: int64

In [14]:
df["NumberOfPersonVisiting"].value_counts()

NumberOfPersonVisiting
3    2402
2    1418
4    1026
1      39
5       3
Name: count, dtype: int64

In [15]:
df["NumberOfTrips"].value_counts()

NumberOfTrips
2.0     1464
3.0     1079
1.0      620
4.0      478
5.0      458
6.0      322
7.0      218
8.0      105
19.0       1
21.0       1
20.0       1
22.0       1
Name: count, dtype: int64

In [16]:
df["Occupation"].value_counts()

Occupation
Salaried          2368
Small Business    2084
Large Business     434
Free Lancer          2
Name: count, dtype: int64

In [17]:
df["OwnCar"].value_counts()

OwnCar
1    3032
0    1856
Name: count, dtype: int64

In [18]:
df["Passport"].value_counts()

Passport
0    3466
1    1422
Name: count, dtype: int64

In [19]:
df["PitchSatisfactionScore"].value_counts()

PitchSatisfactionScore
3    1478
5     970
1     942
4     912
2     586
Name: count, dtype: int64

In [20]:
df["PreferredPropertyStar"].value_counts()

PreferredPropertyStar
3.0    2993
5.0     956
4.0     913
Name: count, dtype: int64

In [21]:
df["ProdTaken"].value_counts()

ProdTaken
0    3968
1     920
Name: count, dtype: int64

In [22]:
df["ProductPitched"].value_counts()

ProductPitched
Basic           1842
Deluxe          1732
Standard         742
Super Deluxe     342
King             230
Name: count, dtype: int64

In [23]:
df['Gender']=df['Gender'].replace('Fe Male','Female')
df['MaritalStatus']=df['MaritalStatus'].replace('Single','Unmarried')

In [24]:
df.head()

,CustomerID,ProdTaken,Age,TypeofContact,CityTier,DurationOfPitch,Occupation,Gender,NumberOfPersonVisiting,NumberOfFollowups,ProductPitched,PreferredPropertyStar,MaritalStatus,NumberOfTrips,Passport,PitchSatisfactionScore,OwnCar,NumberOfChildrenVisiting,Designation,MonthlyIncome
0,200000,1,41.0,Self Enquiry,3,6.0,Salaried,Female,3,3.0,Deluxe,3.0,Unmarried,1.0,1,2,1,0.0,Manager,20993.0
1,200001,0,49.0,Company Invited,1,14.0,Salaried,Male,3,4.0,Deluxe,4.0,Divorced,2.0,0,3,1,2.0,Manager,20130.0
2,200002,1,37.0,Self Enquiry,1,8.0,Free Lancer,Male,3,4.0,Basic,3.0,Unmarried,7.0,1,3,0,0.0,Executive,17090.0
3,200003,0,33.0,Company Invited,1,9.0,Salaried,Female,2,3.0,Basic,3.0,Divorced,2.0,1,5,1,1.0,Executive,17909.0
4,200004,0,NaN,Self Enquiry,1,8.0,Small Business,Male,2,3.0,Basic,4.0,Divorced,1.0,0,5,1,0.0,Executive,18468.0

In [25]:
df['Gender'].value_counts()

Gender
Male      2916
Female    1972
Name: count, dtype: int64

In [26]:
df['MaritalStatus'].value_counts()

MaritalStatus
Married      2340
Unmarried    1598
Divorced      950
Name: count, dtype: int64

### Checking Missing values

In [27]:
features_with_na=[features for features in df.columns if df[features].isnull().sum()>=1]
for feature in features_with_na:
    print(feature,np.round(df[feature].isnull().mean()*100,5))

Age 4.62357
TypeofContact 0.51146
DurationOfPitch 5.13502
NumberOfFollowups 0.92062
PreferredPropertyStar 0.53191
NumberOfTrips 2.86416
NumberOfChildrenVisiting 1.35025
MonthlyIncome 4.76678

In [28]:
df[features_with_na].select_dtypes(exclude='object').describe()

,Age,DurationOfPitch,NumberOfFollowups,PreferredPropertyStar,NumberOfTrips,NumberOfChildrenVisiting,MonthlyIncome
count,4662.000000,4637.000000,4843.000000,4862.000000,4748.000000,4822.000000,4655.000000
mean,37.622265,15.490835,3.708445,3.581037,3.236521,1.187267,23619.853491
std,9.316387,8.519643,1.002509,0.798009,1.849019,0.857861,5380.698361
min,18.000000,5.000000,1.000000,3.000000,1.000000,0.000000,1000.000000
25%,31.000000,9.000000,3.000000,3.000000,2.000000,1.000000,20346.000000
50%,36.000000,13.000000,4.000000,3.000000,3.000000,1.000000,22347.000000
75%,44.000000,20.000000,4.000000,4.000000,4.000000,2.000000,25571.000000
max,61.000000,127.000000,6.000000,5.000000,22.000000,3.000000,98678.000000

## Inputing Null Values

In [29]:
# Age
df.Age.fillna(df.Age.median(),inplace=True)
df.TypeofContact.fillna(df.TypeofContact.mode()[0],inplace=True)
df.DurationOfPitch.fillna(df.DurationOfPitch.median(),inplace=True)
df.NumberOfFollowups.fillna(df.NumberOfFollowups.mode()[0],inplace=True)
df.PreferredPropertyStar.fillna(df.PreferredPropertyStar.mode()[0],inplace=True)
df.NumberOfTrips.fillna(df.NumberOfTrips.median(),inplace=True)
df.NumberOfChildrenVisiting.fillna(df.NumberOfChildrenVisiting.mode()[0],inplace=True)
df.MonthlyIncome.fillna(df.MonthlyIncome.median(),inplace=True)

In [30]:
df.head()

,CustomerID,ProdTaken,Age,TypeofContact,CityTier,DurationOfPitch,Occupation,Gender,NumberOfPersonVisiting,NumberOfFollowups,ProductPitched,PreferredPropertyStar,MaritalStatus,NumberOfTrips,Passport,PitchSatisfactionScore,OwnCar,NumberOfChildrenVisiting,Designation,MonthlyIncome
0,200000,1,41.0,Self Enquiry,3,6.0,Salaried,Female,3,3.0,Deluxe,3.0,Unmarried,1.0,1,2,1,0.0,Manager,20993.0
1,200001,0,49.0,Company Invited,1,14.0,Salaried,Male,3,4.0,Deluxe,4.0,Divorced,2.0,0,3,1,2.0,Manager,20130.0
2,200002,1,37.0,Self Enquiry,1,8.0,Free Lancer,Male,3,4.0,Basic,3.0,Unmarried,7.0,1,3,0,0.0,Executive,17090.0
3,200003,0,33.0,Company Invited,1,9.0,Salaried,Female,2,3.0,Basic,3.0,Divorced,2.0,1,5,1,1.0,Executive,17909.0
4,200004,0,36.0,Self Enquiry,1,8.0,Small Business,Male,2,3.0,Basic,4.0,Divorced,1.0,0,5,1,0.0,Executive,18468.0

In [31]:
df.isnull().sum()

CustomerID                  0
ProdTaken                   0
Age                         0
TypeofContact               0
CityTier                    0
DurationOfPitch             0
Occupation                  0
Gender                      0
NumberOfPersonVisiting      0
NumberOfFollowups           0
ProductPitched              0
PreferredPropertyStar       0
MaritalStatus               0
NumberOfTrips               0
Passport                    0
PitchSatisfactionScore      0
OwnCar                      0
NumberOfChildrenVisiting    0
Designation                 0
MonthlyIncome               0
dtype: int64

In [32]:
df.drop('CustomerID',inplace=True,axis=1)

In [33]:
df.head()

,ProdTaken,Age,TypeofContact,CityTier,DurationOfPitch,Occupation,Gender,NumberOfPersonVisiting,NumberOfFollowups,ProductPitched,PreferredPropertyStar,MaritalStatus,NumberOfTrips,Passport,PitchSatisfactionScore,OwnCar,NumberOfChildrenVisiting,Designation,MonthlyIncome
0,1,41.0,Self Enquiry,3,6.0,Salaried,Female,3,3.0,Deluxe,3.0,Unmarried,1.0,1,2,1,0.0,Manager,20993.0
1,0,49.0,Company Invited,1,14.0,Salaried,Male,3,4.0,Deluxe,4.0,Divorced,2.0,0,3,1,2.0,Manager,20130.0
2,1,37.0,Self Enquiry,1,8.0,Free Lancer,Male,3,4.0,Basic,3.0,Unmarried,7.0,1,3,0,0.0,Executive,17090.0
3,0,33.0,Company Invited,1,9.0,Salaried,Female,2,3.0,Basic,3.0,Divorced,2.0,1,5,1,1.0,Executive,17909.0
4,0,36.0,Self Enquiry,1,8.0,Small Business,Male,2,3.0,Basic,4.0,Divorced,1.0,0,5,1,0.0,Executive,18468.0

## Feature Engineering

In [34]:
df['TotalVisiting']=df['NumberOfPersonVisiting']+df['NumberOfChildrenVisiting']
df.drop(columns=['NumberOfPersonVisiting','NumberOfChildrenVisiting'],axis=1,inplace=True)

In [35]:
df.head()

,ProdTaken,Age,TypeofContact,CityTier,DurationOfPitch,Occupation,Gender,NumberOfFollowups,ProductPitched,PreferredPropertyStar,MaritalStatus,NumberOfTrips,Passport,PitchSatisfactionScore,OwnCar,Designation,MonthlyIncome,TotalVisiting
0,1,41.0,Self Enquiry,3,6.0,Salaried,Female,3.0,Deluxe,3.0,Unmarried,1.0,1,2,1,Manager,20993.0,3.0
1,0,49.0,Company Invited,1,14.0,Salaried,Male,4.0,Deluxe,4.0,Divorced,2.0,0,3,1,Manager,20130.0,5.0
2,1,37.0,Self Enquiry,1,8.0,Free Lancer,Male,4.0,Basic,3.0,Unmarried,7.0,1,3,0,Executive,17090.0,3.0
3,0,33.0,Company Invited,1,9.0,Salaried,Female,3.0,Basic,3.0,Divorced,2.0,1,5,1,Executive,17909.0,3.0
4,0,36.0,Self Enquiry,1,8.0,Small Business,Male,3.0,Basic,4.0,Divorced,1.0,0,5,1,Executive,18468.0,2.0

In [36]:
#get all the numeric features
num_features=[feature for feature in df.columns if df[feature].dtype != 'O']
print("Number of Numerical Features: ",len(num_features))

Number of Numerical Features:  12

In [37]:
#get all the categorical features
cat_features=[feature for feature in df.columns if df[feature].dtype == 'O']
print("Number of Categorical Features: ",len(cat_features))

Number of Categorical Features:  6

In [38]:
#get all the discrete features
discrete_features=[feature for feature in num_features if len(df[feature].unique())<=25]
print("Number of Discrete Features: ",len(discrete_features))

Number of Discrete Features:  9

In [39]:
# Continous Features
continuous_features=[feature for feature in num_features if feature not in discrete_features]
print("Number of Continouous Features: ",len(continuous_features))

Number of Continouous Features:  3

In [40]:
df.head()

,ProdTaken,Age,TypeofContact,CityTier,DurationOfPitch,Occupation,Gender,NumberOfFollowups,ProductPitched,PreferredPropertyStar,MaritalStatus,NumberOfTrips,Passport,PitchSatisfactionScore,OwnCar,Designation,MonthlyIncome,TotalVisiting
0,1,41.0,Self Enquiry,3,6.0,Salaried,Female,3.0,Deluxe,3.0,Unmarried,1.0,1,2,1,Manager,20993.0,3.0
1,0,49.0,Company Invited,1,14.0,Salaried,Male,4.0,Deluxe,4.0,Divorced,2.0,0,3,1,Manager,20130.0,5.0
2,1,37.0,Self Enquiry,1,8.0,Free Lancer,Male,4.0,Basic,3.0,Unmarried,7.0,1,3,0,Executive,17090.0,3.0
3,0,33.0,Company Invited,1,9.0,Salaried,Female,3.0,Basic,3.0,Divorced,2.0,1,5,1,Executive,17909.0,3.0
4,0,36.0,Self Enquiry,1,8.0,Small Business,Male,3.0,Basic,4.0,Divorced,1.0,0,5,1,Executive,18468.0,2.0

## Train Test Split And Model Training

In [41]:
from sklearn.model_selection import train_test_split
X=df.drop(['ProdTaken'],axis=1)
y=df['ProdTaken']

In [42]:
y.value_counts()

ProdTaken
0    3968
1     920
Name: count, dtype: int64

In [43]:
X.head()

,Age,TypeofContact,CityTier,DurationOfPitch,Occupation,Gender,NumberOfFollowups,ProductPitched,PreferredPropertyStar,MaritalStatus,NumberOfTrips,Passport,PitchSatisfactionScore,OwnCar,Designation,MonthlyIncome,TotalVisiting
0,41.0,Self Enquiry,3,6.0,Salaried,Female,3.0,Deluxe,3.0,Unmarried,1.0,1,2,1,Manager,20993.0,3.0
1,49.0,Company Invited,1,14.0,Salaried,Male,4.0,Deluxe,4.0,Divorced,2.0,0,3,1,Manager,20130.0,5.0
2,37.0,Self Enquiry,1,8.0,Free Lancer,Male,4.0,Basic,3.0,Unmarried,7.0,1,3,0,Executive,17090.0,3.0
3,33.0,Company Invited,1,9.0,Salaried,Female,3.0,Basic,3.0,Divorced,2.0,1,5,1,Executive,17909.0,3.0
4,36.0,Self Enquiry,1,8.0,Small Business,Male,3.0,Basic,4.0,Divorced,1.0,0,5,1,Executive,18468.0,2.0

In [44]:
X_train,X_test,y_train,y_test= train_test_split(X,y,test_size=0.2,random_state=42)
X_train.shape,X_test.shape

((3910, 17), (978, 17))

In [45]:
X.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4888 entries, 0 to 4887
Data columns (total 17 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Age                     4888 non-null   float64
 1   TypeofContact           4888 non-null   object
 2   CityTier                4888 non-null   int64
 3   DurationOfPitch         4888 non-null   float64
 4   Occupation              4888 non-null   object
 5   Gender                  4888 non-null   object
 6   NumberOfFollowups       4888 non-null   float64
 7   ProductPitched          4888 non-null   object
 8   PreferredPropertyStar   4888 non-null   float64
 9   MaritalStatus           4888 non-null   object
 10  NumberOfTrips           4888 non-null   float64
 11  Passport                4888 non-null   int64
 12  PitchSatisfactionScore  4888 non-null   int64
 13  OwnCar                  4888 non-null   int64
 14  Designation             4888 non-null   object
 15  MonthlyIncome           4888 non-null   float64
 16  TotalVisiting           4888 non-null   float64
dtypes: float64(7), int64(4), object(6)
memory usage: 649.3+ KB

In [46]:
cat_features=X.select_dtypes(include='object').columns
num_features=X.select_dtypes(exclude='object').columns

from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.compose import ColumnTransformer

numeric_transformer=StandardScaler()
oh_transformer=OneHotEncoder(drop='first')

preprocessor= ColumnTransformer(
    [
        ("OneHotEncoder",oh_transformer,cat_features),
        ("StandardScaler",numeric_transformer,num_features)
    ]
)

In [47]:
# applying Transformtion 
X_train=preprocessor.fit_transform(X_train)
X_test=preprocessor.transform(X_test)

In [48]:
pd.DataFrame(X_train)

,0,1,2,3,4,5,6,7,8,9,...,16,17,18,19,20,21,22,23,24,25
0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,...,-0.721400,-1.020350,1.284279,-0.725271,-0.127737,-0.632399,0.679690,0.782966,-0.382245,-0.774151
1,1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,...,-0.721400,0.690023,0.282777,-0.725271,1.511598,-0.632399,0.679690,0.782966,-0.459799,0.643615
2,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,-0.721400,-1.020350,0.282777,1.771041,0.418708,-0.632399,0.679690,0.782966,-0.245196,-0.065268
3,1.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,...,-0.721400,-1.020350,1.284279,-0.725271,-0.127737,-0.632399,1.408395,-1.277194,0.213475,-0.065268
4,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,-0.721400,2.400396,-1.720227,-0.725271,1.511598,-0.632399,-0.049015,-1.277194,-0.024889,2.061382
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3905,1.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,...,-0.721400,-0.653841,1.284279,-0.725271,-0.674182,-0.632399,-1.506426,0.782966,-0.536973,0.643615
3906,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,1.455047,-0.898180,-0.718725,1.771041,-1.220627,-0.632399,1.408395,0.782966,1.529609,-0.065268
3907,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.455047,1.545210,0.282777,-0.725271,2.058043,-0.632399,-0.777720,0.782966,-0.360576,0.643615
3908,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,...,1.455047,1.789549,1.284279,-0.725271,-0.127737,-0.632399,-1.506426,0.782966,-0.252799,0.643615
3909,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,-0.721400,-0.776011,0.282777,-0.725271,-1.220627,1.581280,-0.049015,-1.277194,-1.082511,-1.483035

## Random forest Classifier Training

In [49]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.metrics import accuracy_score,classification_report,ConfusionMatrixDisplay,precision_score,recall_score,f1_score,roc_auc_score,roc_curve

In [50]:
models={
    "Logistic Regression":LogisticRegression(),
    "Decision Tree":DecisionTreeClassifier(),
    "Random Forest":RandomForestClassifier(),
    "Adaboost" : AdaBoostClassifier()
}
for i in range(len(list(models))):
    model=list(models.values())[i]
    model.fit(X_train,y_train)# Train the model

    # make predictions
    y_train_pred=model.predict(X_train)
    y_test_pred=model.predict(X_test)

    # Training set Performance
    model_train_accuracy=accuracy_score(y_train,y_train_pred)
    model_train_f1=f1_score(y_train,y_train_pred)
    model_train_precision=precision_score(y_train,y_train_pred)
    model_train_recall=recall_score(y_train,y_train_pred)
    model_train_roc_auc_score=roc_auc_score(y_train,y_train_pred)

    # Testing set Performance
    model_test_accuracy=accuracy_score(y_test,y_test_pred)
    model_test_f1=f1_score(y_test,y_test_pred)
    model_test_precision=precision_score(y_test,y_test_pred)
    model_test_recall=recall_score(y_test,y_test_pred)
    model_test_roc_auc_score=roc_auc_score(y_test,y_test_pred)

    print(list(models.keys())[i])

    print("-----------------------------------")
    print("-----------------------------------")
    print("Model Performance for Training set: ")
    print("-Accuracy:",model_train_accuracy)
    print("-F1 Score :",model_train_f1)
    print("-Preicsion:",model_train_precision)
    print("-Recall:",model_train_recall)
    print("-Roc auc Score:",model_train_roc_auc_score)


    print("-----------------------------------")
    print("-----------------------------------")
    print("Model Performance for Testing set: ")
    print("-Accuracy:",model_test_accuracy)
    print("-F1 Score :",model_test_f1)
    print("-Preicsion:",model_test_precision)
    print("-Recall:",model_test_recall)
    print("-Roc auc Score:",model_test_roc_auc_score)

    print("-----------------------------------")
    print("-----------------------------------")

Logistic Regression
-----------------------------------
-----------------------------------
Model Performance for Training set:
-Accuracy: 0.8460358056265984
-F1 Score : 0.42337164750957856
-Preicsion: 0.7015873015873015
-Recall: 0.30315500685871055
-Roc auc Score: 0.6368022755136056
-----------------------------------
-----------------------------------
Model Performance for Testing set:
-Accuracy: 0.83640081799591
-F1 Score : 0.4117647058823529
-Preicsion: 0.691358024691358
-Recall: 0.2931937172774869
-Roc auc Score: 0.630713758257549
-----------------------------------
-----------------------------------
Decision Tree
-----------------------------------
-----------------------------------
Model Performance for Training set:
-Accuracy: 1.0
-F1 Score : 1.0
-Preicsion: 1.0
-Recall: 1.0
-Roc auc Score: 1.0
-----------------------------------
-----------------------------------
Model Performance for Testing set:
-Accuracy: 0.9120654396728016
-F1 Score : 0.7675675675675676
-Preicsion: 0.7932960893854749
-Recall: 0.743455497382199
-Roc auc Score: 0.8482207601269318
-----------------------------------
-----------------------------------
Random Forest
-----------------------------------
-----------------------------------
Model Performance for Training set:
-Accuracy: 1.0
-F1 Score : 1.0
-Preicsion: 1.0
-Recall: 1.0
-Roc auc Score: 1.0
-----------------------------------
-----------------------------------
Model Performance for Testing set:
-Accuracy: 0.9222903885480572
-F1 Score : 0.7610062893081762
-Preicsion: 0.952755905511811
-Recall: 0.6335078534031413
-Roc auc Score: 0.812941982610084
-----------------------------------
-----------------------------------
Adaboost
-----------------------------------
-----------------------------------
Model Performance for Training set:
-Accuracy: 0.8478260869565217
-F1 Score : 0.3846949327817994
-Preicsion: 0.7815126050420168
-Recall: 0.2551440329218107
-Roc auc Score: 0.6193984861245332
-----------------------------------
-----------------------------------
Model Performance for Testing set:
-Accuracy: 0.8353783231083844
-F1 Score : 0.35856573705179284
-Preicsion: 0.75
-Recall: 0.2356020942408377
-Roc auc Score: 0.6082711868917022
-----------------------------------
-----------------------------------

## Hyperparameter Tuning

In [51]:
rf_params={
    "n_estimators": [100,200,500,1000],
    "max_depth":[5,7,8],
    "min_samples_split" :[2,5,15,30],
    "max_features":['sqrt', 'log2', None]
}
adaboost_params={
    "n_estimators": [100,200,500,1000],
    "algorithm":["SAMME", "SAMME.R"]
}

In [52]:
rf_params

{'n_estimators': [100, 200, 500, 1000],
 'max_depth': [5, 7, 8],
 'min_samples_split': [2, 5, 15, 30],
 'max_features': ['sqrt', 'log2', None]}

In [53]:
adaboost_params

{'n_estimators': [100, 200, 500, 1000], 'algorithm': ['SAMME', 'SAMME.R']}

In [54]:
random_cv_models=[
    ("RF", RandomForestClassifier(),rf_params),
    ("AB", AdaBoostClassifier(),adaboost_params),
]

In [55]:
random_cv_models

[('RF',
  RandomForestClassifier(),
  {'n_estimators': [100, 200, 500, 1000],
   'max_depth': [5, 7, 8],
   'min_samples_split': [2, 5, 15, 30],
   'max_features': ['sqrt', 'log2', None]}),
 ('AB',
  AdaBoostClassifier(),
  {'n_estimators': [100, 200, 500, 1000], 'algorithm': ['SAMME', 'SAMME.R']})]

In [56]:
from sklearn.model_selection import RandomizedSearchCV

model_param={}
for name,model, params in random_cv_models:
    random= RandomizedSearchCV(estimator=model,
                           param_distributions=params,
                           n_iter=100,
                           cv=3,
                           verbose=2,
                           n_jobs=-1)
    random.fit(X_train,y_train)
    model_param[name]=random.best_params_

for model_name in model_param:
    print(f"--------------------------BEST PARAMS FOR {model_name}----------------------------")
    print(model_param[model_name])

Fitting 3 folds for each of 100 candidates, totalling 300 fits
Fitting 3 folds for each of 8 candidates, totalling 24 fits
--------------------------BEST PARAMS FOR RF----------------------------
{'n_estimators': 200, 'min_samples_split': 2, 'max_features': None, 'max_depth': 8}
--------------------------BEST PARAMS FOR AB----------------------------
{'n_estimators': 100, 'algorithm': 'SAMME'}

In [59]:
models={
    "Random Forest" : RandomForestClassifier(n_estimators=1000,
                                             min_samples_split=2,
                                             max_features=None,
                                             max_depth=8),
    "Adaboost" : AdaBoostClassifier(n_estimators=100,
                                     algorithm="SAMME")
}
for i in range(len(list(models))):
    model=list(models.values())[i]
    model.fit(X_train,y_train)# Train the model

    # make predictions
    y_train_pred=model.predict(X_train)
    y_test_pred=model.predict(X_test)

    # Training set Performance
    model_train_accuracy=accuracy_score(y_train,y_train_pred)
    model_train_f1=f1_score(y_train,y_train_pred)
    model_train_precision=precision_score(y_train,y_train_pred)
    model_train_recall=recall_score(y_train,y_train_pred)
    model_train_roc_auc_score=roc_auc_score(y_train,y_train_pred)

    # Testing set Performance
    model_test_accuracy=accuracy_score(y_test,y_test_pred)
    model_test_f1=f1_score(y_test,y_test_pred)
    model_test_precision=precision_score(y_test,y_test_pred)
    model_test_recall=recall_score(y_test,y_test_pred)
    model_test_roc_auc_score=roc_auc_score(y_test,y_test_pred)

    print(list(models.keys())[i])

    print("-----------------------------------")
    print("-----------------------------------")
    print("Model Performance for Training set: ")
    print("-Accuracy:",model_train_accuracy)
    print("-F1 Score :",model_train_f1)
    print("-Preicsion:",model_train_precision)
    print("-Recall:",model_train_recall)
    print("-Roc auc Score:",model_train_roc_auc_score)


    print("-----------------------------------")
    print("-----------------------------------")
    print("Model Performance for Testing set: ")
    print("-Accuracy:",model_test_accuracy)
    print("-F1 Score :",model_test_f1)
    print("-Preicsion:",model_test_precision)
    print("-Recall:",model_test_recall)
    print("-Roc auc Score:",model_test_roc_auc_score)

    print("-----------------------------------")
    print("-----------------------------------")

Random Forest
-----------------------------------
-----------------------------------
Model Performance for Training set:
-Accuracy: 0.9360613810741688
-F1 Score : 0.7947454844006568
-Preicsion: 0.9897750511247444
-Recall: 0.663923182441701
-Roc auc Score: 0.8311756748423531
-----------------------------------
-----------------------------------
Model Performance for Testing set:
-Accuracy: 0.8997955010224948
-F1 Score : 0.6797385620915033
-Preicsion: 0.9043478260869565
-Recall: 0.5445026178010471
-Roc auc Score: 0.7652627447327981
-----------------------------------
-----------------------------------
Adaboost
-----------------------------------
-----------------------------------
Model Performance for Training set:
-Accuracy: 0.8483375959079283
-F1 Score : 0.3930399181166837
-Preicsion: 0.7741935483870968
-Recall: 0.26337448559670784
-Roc auc Score: 0.6228849793591839
-----------------------------------
-----------------------------------
Model Performance for Testing set:
-Accuracy: 0.8384458077709611
-F1 Score : 0.3629032258064516
-Preicsion: 0.7894736842105263
-Recall: 0.2356020942408377
-Roc auc Score: 0.6101771589374455
-----------------------------------
-----------------------------------